"""Localized UI strings for Russian and English. / Локализованные строки интерфейса на русском и английском."""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from core import config

STRINGS = {
    "ru": {
        "app_title": "CryptoSafe Manager",
        "file": "Файл", "new": "Новый", "open": "Открыть", "unlock": "Разблокировать", "backup": "Резервная копия", "exit": "Выход",
        "edit": "Правка", "add": "Добавить", "edit_": "Изменить", "delete": "Удалить", "copy_login": "Копировать логин", "copy_password": "Копировать пароль",
        "view": "Вид", "logs": "Журнал", "settings": "Настройки", "state_monitor": "Монитор состояния",
        "help": "Справка",
        "status_locked": "Заблокировано", "status_unlocked": "Разблокировано",
        "buffer_timer": "Буфер: %s с",
        "title": "Название", "login": "Логин", "url": "URL", "notes": "Заметки", "password_field": "Пароль", "title_required": "Название — обязательное поле.", "select_entry_edit": "Выберите запись для редактирования.", "select_entry_delete": "Выберите запись для удаления.", "confirm_delete": "Удалить выбранную запись?",
        "security": "Безопасность", "appearance": "Внешний вид", "advanced": "Дополнительно",
        "clipboard_timeout": "Таймаут буфера (сек)", "auto_lock": "Автоблокировка (мин)",
        "theme": "Тема", "language": "Язык", "theme_system": "Системная", "theme_dark": "Тёмная", "theme_light": "Светлая",
        "master_password": "Мастер-пароль", "confirm_password": "Подтверждение",
        "db_location": "Расположение базы данных", "db_location_required": "Выберите расположение базы данных.", "encryption_settings": "Настройки шифрования",
        "backup_export": "Резервная копия и экспорт",
        "backup_export_hint": "Архив .csafe.zip — полная копия vault.db (и настроек при создании). Экспорт хранилища — выбор формата и записей. То же доступно в меню «Файл».",
        "backup_export_unavailable": "Откройте настройки из главного окна приложения.",
        "apply": "Применить", "cancel": "Отмена", "ok": "ОК",
        "about": "О программе", "about_text": "CryptoSafe Manager\nЛокальный менеджер паролей.", "enter_master_password": "Введите мастер-пароль:", "master_password_hint": "Мастер-пароль задаётся при первой настройке (мастер первого запуска), не путать с паролями записей в таблице.", "login_title": "Вход", "password_required": "Введите мастер-пароль. Поле не может быть пустым.",         "setup_first": "Сначала выполните первичную настройку (мастер-пароль ещё не задан).", "wrong_password": "Неверный мастер-пароль.",
        "wrong_password_attempts": "Неверный мастер-пароль. Неудачных попыток: %s. После 5 попыток вход будет замедлен.",
        "error_generic": "Произошла ошибка. Повторите действие.",
        "session_locked_action": "Сессия заблокирована. Выберите «Файл → Разблокировать» и введите мастер-пароль.",
        "vault_empty": "В хранилище пока нет записей.",
        "vault_empty_hint": "Добавьте первую запись: меню «Правка → Добавить».",
        "vault_empty_search": "По запросу ничего не найдено.",
        "db_not_found": "Файл базы данных не найден. Укажите путь в настройках или выполните первичную настройку.",
        "err_timeout": "Операция заняла слишком много времени. Попробуйте файл меньшего размера.",
        "err_file_not_found": "Файл не найден. Проверьте путь и повторите.",
        "err_permission": "Нет доступа к файлу. Закройте его в других программах или выберите другую папку.",
        "err_file_too_large": "Файл слишком большой (лимит 10 МБ).",
        "err_wrong_master_password": "Неверный мастер-пароль для этой операции.",
        "s6_export_failed_generic": "Не удалось выполнить экспорт. Проверьте пароли и выбранные записи.",
        "s6_import_failed_generic": "Не удалось выполнить импорт. Проверьте формат файла и пароли.",
        "s6_share_failed_generic": "Не удалось создать пакет для обмена.",
        "s6_qr_failed_generic": "Не удалось обработать QR-данные.",
        "s6_no_entries_selected": "Выберите хотя бы одну запись для экспорта.",
        "s6_preview_failed_generic": "Не удалось прочитать файл. Проверьте формат и пароли.",
        "password_too_long": "Пароль слишком длинный.", "passwords_dont_match": "Пароли не совпадают.",
        "state_session": "Сессия:", "state_clipboard": "Таймер буфера (с):", "state_inactivity": "Неактивность (с):",
        "change_password_title": "Сменить пароль", "current_password": "Текущий пароль", "new_password": "Новый пароль", "change_password_ok": "Пароль успешно изменён.",
        "session_locked_inactivity": "Сессия заблокирована из-за неактивности. Введите пароль в меню «Разблокировать».",
        "session_locked_manual": "Сессия заблокирована. Введите мастер-пароль в меню «Разблокировать».",
        "clipboard_toolbar_title": "Буфер обмена",
        "clipboard_toolbar_show_passwords": "Показать пароли",
        "password_show": "Показать",
        "password_hide": "Скрыть",
        "password_btn_show": "Пок.",
        "password_btn_hide": "Скр.",
        "clipboard_copy_all": "Копировать всё",
        "clipboard_copied_status": "Скопировано: %s (очистка через %s с)",
        "clipboard_copied_type": "Скопировано: %s",
        "clipboard_cleared_status": "Буфер обмена очищен",
        "clipboard_warning_soon_clear": "Буфер очистится через 5 секунд",
        "clipboard_preview_hidden": "Предпросмотр: %s из записи \"%s\"",
        "clipboard_preview_revealed": "Предпросмотр: %s",
        "clipboard_manual_clear": "Очистить буфер",
        "clipboard_status_idle": "Буфер: пусто",
        "clipboard_source_unknown": "без источника",
        "search_placeholder": "название:, логин:, url:, заметки:...  |  поиск",
        "unit_seconds": " сек",
        "unit_minutes": " мин",
        "password_generate": "Сгенерировать пароль",
        "password_strength": "Надёжность: %d/4",
        "last_modified": "Последнее изменение",
        "category": "Категория",
        "category_optional": "Категория (необязательно)",
        "length": "Длина",
        "upper": "Верхний регистр A-Z",
        "lower": "Нижний регистр a-z",
        "digits": "Цифры 0-9",
        "symbols": "Символы !@#$%^&*",
        "exclude_ambiguous": "Исключить похожие (l I 1 0 O)",
        "invalid_url": "Некорректный URL (нужен http/https)",
        "notifications_enabled": "Уведомления буфера",
        "security_level": "Уровень безопасности",
        "security_profile_hint": "Пресет нескольких настроек сразу.",
        "security_level_hint": "Буфер: basic — только таймер; advanced — подмена + whitelist; paranoid — строже, whitelist не действует.",
        "clipboard_whitelist_hint": "Имена процессов через запятую (chrome.exe). Учитывается при уровне «Продвинутый».",
        "lock_session": "Заблокировать",
        "keyboard_shortcuts": "Горячие клавиши",
        "shortcuts_help_title": "Горячие клавиши и навигация",
        "shortcuts_nav_hint": "Tab — переход между поиском и таблицей; стрелки — строки и колонки; Enter/F2 в таблице — изменить запись.",
        "shortcut_add": "Добавить запись",
        "shortcut_edit": "Изменить выбранную запись",
        "shortcut_edit_enter": "Изменить запись (фокус в таблице)",
        "shortcut_delete": "Удалить выбранную запись (фокус в таблице)",
        "shortcut_focus_search": "Перейти к поиску",
        "shortcut_escape_search": "Очистить поиск (фокус в поле поиска)",
        "shortcut_copy_login": "Копировать логин",
        "shortcut_copy_password": "Копировать пароль",
        "shortcut_copy_all": "Копировать все поля",
        "shortcut_clear_clipboard": "Очистить буфер обмена",
        "shortcut_show_passwords": "Показать/скрыть пароли в таблице",
        "shortcut_unlock": "Разблокировать хранилище",
        "shortcut_lock": "Заблокировать хранилище",
        "shortcut_audit_log": "Журнал аудита",
        "shortcut_settings": "Настройки",
        "shortcut_panic": "Режим паники",
        "search_accessible": "Поиск по записям",
        "vault_table_accessible": "Таблица записей хранилища",
        "activity_sensitivity_hint": "Скорость учёта простоя.",
        "sens_low": "Низкая",
        "sens_medium": "Средняя",
        "sens_high": "Высокая",
        "security_basic": "Базовый",
        "security_advanced": "Продвинутый",
        "security_paranoid": "Параноидальный",
        "clipboard_whitelist": "Whitelist приложений",
        "clipboard_staged_status": "Секрет подготовлен. Вставка в буфер: Ctrl+Shift+V, затем Ctrl+V в нужном окне",
        "clipboard_commit_paste": "Поместить в буфер (Ctrl+Shift+V)",
        "clipboard_committed_status": "Секрет в буфере — очистится по таймеру",
        "clipboard_nothing_staged": "Нет подготовленного секрета для вставки",
        "clipboard_staged_indicator": "Ожидание вставки: %s (%s с)",
        "audit_filter_label": "Событие",
        "audit_filter_all": "Все",
        "audit_verify": "Проверить целостность",
        "audit_verifying": "Проверка целостности…",
        "audit_empty": "Журнал пуст — проверять нечего.",
        "audit_integrity_partial": "Проверены последние %s из %s записей.",
        "audit_export_json": "Экспорт",
        "audit_export_done": "Журнал экспортирован",
        "audit_integrity_ok": "Целостность OK (%s / %s записей)",
        "audit_integrity_fail": "Обнаружены нарушения: %s",
        "audit_integrity_error": "Не удалось проверить журнал",
        "audit_integrity_unknown": "Целостность: не проверялась",
        "audit_col_time": "Время",
        "audit_col_event": "Событие",
        "audit_col_severity": "Уровень",
        "audit_col_details": "Детали",
        "audit_col_entry": "Запись",
        "audit_tamper_title": "Журнал аудита",
        "audit_tamper_message": "Обнаружено возможное изменение журнала аудита. Проверьте раздел «Журнал».",
        "s6_export": "Экспорт хранилища",
        "s6_import": "Импорт в хранилище",
        "s6_share": "Поделиться записью",
        "s6_qr_viewer": "QR просмотрщик",
        "restore_backup": "Восстановить из копии",
        "backup_ok": "Резервная копия создана:\n%s",
        "backup_failed_generic": "Не удалось создать резервную копию. Закройте vault.db в других программах и повторите.",
        "backup_save_filter": "Архив CryptoSafe (*.csafe.zip)",
        "restore_ok": "Восстановление завершено.\n\nВведите мастер-пароль от момента создания этой копии (не новый пароль, если вы его меняли после бэкапа). Сейчас откроется окно входа.",
        "restore_wrong_password_hint": "Если вход не принимается — вы восстановили копию другого хранилища или пароль не совпадает с датой резервной копии.",
        "security_profile": "Профиль безопасности",
        "profile_standard": "Стандартный",
        "profile_enhanced": "Усиленный",
        "profile_paranoid": "Параноидальный",
        "profile_desc": "Описание профиля",
        "minimize_to_tray": "Сворачивать в трей при минимизации (не при закрытии)",
        "start_minimized_tray": "Запуск в трее",
        "panic_hotkey": "Горячая клавиша паники (Ctrl+Shift+Esc)",
        "panic_stealth": "Скрытый режим паники (фиктивная ошибка)",
        "activity_sensitivity": "Чувствительность активности",
        "device_laptop": "Ноутбук",
        "device_desktop": "ПК",
        "tray_show": "Показать окно",
        "tray_lock": "Заблокировать",
        "tray_unlock": "Разблокировать",
        "tray_clear_clipboard": "Очистить буфер",
        "tray_panic": "Режим паники",
        "tray_tooltip_locked": "CryptoSafe — заблокировано",
        "tray_tooltip_unlocked": "CryptoSafe — разблокировано",
        "panic_activated": "Режим паники: хранилище заблокировано.",
        "confirm_restore": "Восстановить хранилище из резервной копии? Текущая БД будет перезаписана.",
        "confirm_destructive": "Подтвердите действие",
        "profile_desc_standard": "Баланс (рекомендуется).",
        "profile_desc_enhanced": "Короче таймауты, блок при сворачивании.",
        "profile_desc_paranoid": "Макс. защита, быстрая блокировка.",
        "device_profile_label": "Тип устройства",
        "s6_export_title": "Экспорт хранилища",
        "s6_import_title": "Импорт в хранилище",
        "s6_share_title": "Поделиться записью",
        "s6_qr_title": "QR просмотрщик",
        "s6_format": "Формат",
        "s6_export_password": "Пароль экспорта",
        "s6_public_key": "Публичный ключ получателя",
        "s6_public_key_ph": "Необязательно: ключ RSA получателя (из файла или QR)",
        "s6_private_key": "Закрытый ключ",
        "s6_private_key_ph": "Необязательно: ваш закрытый ключ RSA при импорте",
        "s6_encryption_settings": "Параметры шифрования",
        "s6_aes_bits": "AES, бит",
        "s6_gzip": "Сжатие GZIP",
        "s6_include_notes": "Включать заметки",
        "s6_entry_selection": "Выбор записей",
        "s6_preview": "Предпросмотр",
        "s6_export_btn": "Экспорт",
        "s6_import_btn": "Импорт",
        "s6_browse": "Обзор…",
        "s6_file": "Файл",
        "s6_share_password": "Пароль для share",
        "s6_conflict_mode": "Режим конфликтов",
        "s6_duplicate_policy": "Дубликаты",
        "s6_preview_btn": "Предпросмотр",
        "s6_delivery": "Способ доставки",
        "s6_permission": "Права",
        "s6_expiration_days": "Срок (дней)",
        "s6_generate_share": "Создать share-пакет",
        "s6_payload": "Данные (JSON)",
        "s6_generate_qr": "Сгенерировать QR",
        "s6_scan_image": "Сканировать изображение",
        "s6_copy_payload": "Копировать данные",
        "s6_export_failed": "Ошибка экспорта: %s",
        "s6_import_failed": "Ошибка импорта: %s",
        "s6_share_failed": "Ошибка share: %s",
        "s6_export_done": "Экспорт сохранён: %s",
        "s6_import_done": "Импорт: добавлено %s, обновлено %s, пропущено %s",
        "s6_share_done": "Share-пакет создан",
        "s6_invalid_pem": "Неверный ключ RSA. Оставьте поле пустым или вставьте ключ целиком, как в файле обмена.",
        "s6_select_entry_first": "Сначала выберите запись в таблице.",
        "s6_save_export": "Сохранить экспорт",
        "s6_select_import": "Выберите файл импорта",
        "s6_fmt_encrypted_json": "Encrypted JSON",
        "s6_fmt_csv": "CSV (открытый)",
        "s6_fmt_csv_enc": "CSV (зашифрованный JSON)",
        "s6_fmt_bw": "Bitwarden JSON",
        "s6_fmt_bw_enc": "Bitwarden (зашифрованный)",
        "s6_fmt_lp": "LastPass CSV",
        "s6_fmt_lp_enc": "LastPass (зашифрованный)",
        "s6_mode_merge": "Объединить",
        "s6_mode_replace": "Заменить",
        "s6_mode_dry": "Только проверка",
        "s6_dup_skip": "Пропускать",
        "s6_dup_update": "Обновлять",
        "s6_method_password": "Файл + пароль",
        "s6_method_pubkey": "Публичный ключ RSA",
        "s6_method_link": "Ссылка-токен",
        "s6_perm_readonly": "Только чтение",
        "s6_perm_edit": "Редактирование",
        "s6_qr_failed": "Ошибка QR: %s",
        "s6_preview_failed": "Предпросмотр: %s",
        "s6_col_entry": "Запись",
    },
    "en": {
        "app_title": "CryptoSafe Manager",
        "file": "File", "new": "New", "open": "Open", "unlock": "Unlock", "backup": "Backup", "exit": "Exit",
        "edit": "Edit", "add": "Add", "edit_": "Edit", "delete": "Delete", "copy_login": "Copy login", "copy_password": "Copy password",
        "view": "View", "logs": "Logs", "settings": "Settings", "state_monitor": "State monitor",
        "help": "Help",
        "status_locked": "Locked", "status_unlocked": "Unlocked",
        "buffer_timer": "Buffer: %s s",
        "title": "Title", "login": "Login", "url": "URL", "notes": "Notes", "password_field": "Password", "title_required": "Title is required.", "select_entry_edit": "Select an entry to edit.", "select_entry_delete": "Select an entry to delete.", "confirm_delete": "Delete the selected entry?",
        "security": "Security", "appearance": "Appearance", "advanced": "Advanced",
        "clipboard_timeout": "Clipboard timeout (sec)", "auto_lock": "Auto-lock (min)",
        "theme": "Theme", "language": "Language", "theme_system": "System", "theme_dark": "Dark", "theme_light": "Light",
        "master_password": "Master password", "confirm_password": "Confirm",
        "db_location": "Database location", "db_location_required": "Select database location.", "encryption_settings": "Encryption settings",
        "backup_export": "Backup and export",
        "backup_export_hint": "A .csafe.zip archive is a full vault.db copy (settings included when created). Vault export picks format and entries. Also under File menu.",
        "backup_export_unavailable": "Open Settings from the main application window.",
        "apply": "Apply", "cancel": "Cancel", "ok": "OK",
        "about": "About", "about_text": "CryptoSafe Manager\nLocal password manager.", "enter_master_password": "Enter master password:", "master_password_hint": "Master password is set during first-run setup only; it is not the same as entry passwords in the table.", "login_title": "Login", "password_required": "Enter master password. The field cannot be empty.",         "setup_first": "Complete initial setup first (master password not set).", "wrong_password": "Incorrect master password.",
        "wrong_password_attempts": "Incorrect master password. Failed attempts: %s. After 5 attempts login will be slowed.",
        "error_generic": "An error occurred. Please try again.",
        "session_locked_action": "Session is locked. Use File → Unlock and enter your master password.",
        "vault_empty": "The vault has no entries yet.",
        "vault_empty_hint": "Add your first entry via Edit → Add.",
        "vault_empty_search": "No entries match your search.",
        "db_not_found": "Database file not found. Check the path in settings or run initial setup.",
        "err_timeout": "The operation took too long. Try a smaller file.",
        "err_file_not_found": "File not found. Check the path and try again.",
        "err_permission": "Cannot access the file. Close it in other apps or choose another folder.",
        "err_file_too_large": "File is too large (10 MB limit).",
        "err_wrong_master_password": "Incorrect master password for this operation.",
        "s6_export_failed_generic": "Export failed. Check passwords and selected entries.",
        "s6_import_failed_generic": "Import failed. Check file format and passwords.",
        "s6_share_failed_generic": "Could not create the share package.",
        "s6_qr_failed_generic": "Could not process QR data.",
        "s6_no_entries_selected": "Select at least one entry to export.",
        "s6_preview_failed_generic": "Could not read the file. Check format and passwords.",
        "password_too_long": "Password is too long.", "passwords_dont_match": "Passwords do not match.",
        "state_session": "Session:", "state_clipboard": "Clipboard timer (s):", "state_inactivity": "Inactivity (s):",
        "change_password_title": "Change password", "current_password": "Current password", "new_password": "New password", "change_password_ok": "Password changed successfully.",
        "session_locked_inactivity": "Session locked due to inactivity. Use menu Unlock to enter password.",
        "session_locked_manual": "Session locked. Enter your master password via File → Unlock.",
        "clipboard_toolbar_title": "Clipboard",
        "clipboard_toolbar_show_passwords": "Show passwords",
        "password_show": "Show",
        "password_hide": "Hide",
        "password_btn_show": "Show",
        "password_btn_hide": "Hide",
        "clipboard_copy_all": "Copy all",
        "clipboard_copied_status": "Copied: %s (clears in %s s)",
        "clipboard_copied_type": "Copied: %s",
        "clipboard_cleared_status": "Clipboard cleared",
        "clipboard_warning_soon_clear": "Clipboard will clear in 5 seconds",
        "clipboard_preview_hidden": "Preview: %s from entry \"%s\"",
        "clipboard_preview_revealed": "Preview: %s",
        "clipboard_manual_clear": "Clear clipboard",
        "clipboard_status_idle": "Clipboard: empty",
        "clipboard_source_unknown": "no source",
        "search_placeholder": "title:, username:, url:, notes:...  |  search",
        "unit_seconds": " sec",
        "unit_minutes": " min",
        "password_generate": "Generate password",
        "password_strength": "Strength: %d/4",
        "last_modified": "Last modified",
        "category": "Category",
        "category_optional": "Category (optional)",
        "length": "Length",
        "upper": "Upper A-Z",
        "lower": "Lower a-z",
        "digits": "Digits 0-9",
        "symbols": "Symbols !@#$%^&*",
        "exclude_ambiguous": "Exclude ambiguous (l I 1 0 O)",
        "invalid_url": "Invalid URL (http/https required)",
        "notifications_enabled": "Clipboard notifications",
        "security_level": "Security level",
        "security_profile_hint": "Applies several settings at once.",
        "security_level_hint": "Clipboard: basic — timer only; advanced — tamper + whitelist; paranoid — strict, no whitelist.",
        "clipboard_whitelist_hint": "Process names, comma-separated (chrome.exe). Used at Advanced level.",
        "lock_session": "Lock vault",
        "keyboard_shortcuts": "Keyboard shortcuts",
        "shortcuts_help_title": "Keyboard shortcuts and navigation",
        "shortcuts_nav_hint": "Tab — search and table; arrows — rows/columns; Enter/F2 in table — edit entry.",
        "shortcut_add": "Add entry",
        "shortcut_edit": "Edit selected entry",
        "shortcut_edit_enter": "Edit entry (table focused)",
        "shortcut_delete": "Delete selected entry (table focused)",
        "shortcut_focus_search": "Focus search",
        "shortcut_escape_search": "Clear search (search focused)",
        "shortcut_copy_login": "Copy username",
        "shortcut_copy_password": "Copy password",
        "shortcut_copy_all": "Copy all fields",
        "shortcut_clear_clipboard": "Clear clipboard",
        "shortcut_show_passwords": "Show/hide passwords in table",
        "shortcut_unlock": "Unlock vault",
        "shortcut_lock": "Lock vault",
        "shortcut_audit_log": "Audit log",
        "shortcut_settings": "Settings",
        "shortcut_panic": "Panic mode",
        "search_accessible": "Search entries",
        "vault_table_accessible": "Vault entries table",
        "activity_sensitivity_hint": "How fast idle is detected.",
        "sens_low": "Low",
        "sens_medium": "Medium",
        "sens_high": "High",
        "security_basic": "Basic",
        "security_advanced": "Advanced",
        "security_paranoid": "Paranoid",
        "clipboard_whitelist": "App whitelist",
        "clipboard_staged_status": "Secret prepared. Put on clipboard: Ctrl+Shift+V, then Ctrl+V in target app",
        "clipboard_commit_paste": "Put on clipboard (Ctrl+Shift+V)",
        "clipboard_committed_status": "Secret on clipboard — will clear on timer",
        "clipboard_nothing_staged": "Nothing prepared to paste",
        "clipboard_staged_indicator": "Awaiting paste: %s (%s s)",
        "audit_filter_label": "Event",
        "audit_filter_all": "All",
        "audit_verify": "Verify integrity",
        "audit_verifying": "Verifying integrity…",
        "audit_empty": "Audit log is empty.",
        "audit_integrity_partial": "Checked last %s of %s entries.",
        "audit_export_json": "Export",
        "audit_export_done": "Log exported",
        "audit_integrity_ok": "Integrity OK (%s / %s entries)",
        "audit_integrity_fail": "Violations found: %s",
        "audit_integrity_error": "Could not verify log",
        "audit_integrity_unknown": "Integrity: not checked",
        "audit_col_time": "Time",
        "audit_col_event": "Event",
        "audit_col_severity": "Severity",
        "audit_col_details": "Details",
        "audit_col_entry": "Entry",
        "audit_tamper_title": "Audit log",
        "audit_tamper_message": "Possible audit log tampering detected. Open Logs to review.",
        "s6_export": "Export vault",
        "s6_import": "Import to vault",
        "s6_share": "Share entry",
        "s6_qr_viewer": "QR viewer",
        "restore_backup": "Restore from backup",
        "backup_ok": "Backup created:\n%s",
        "backup_failed_generic": "Could not create backup. Close vault.db in other apps and try again.",
        "backup_save_filter": "CryptoSafe archive (*.csafe.zip)",
        "restore_ok": "Restore complete.\n\nEnter the master password from when this backup was created (not a newer password if you changed it after the backup). The login dialog will open now.",
        "restore_wrong_password_hint": "If login fails, the backup may be from another vault or the password does not match that backup.",
        "security_profile": "Security profile",
        "profile_standard": "Standard",
        "profile_enhanced": "Enhanced",
        "profile_paranoid": "Paranoid",
        "profile_desc": "Profile description",
        "minimize_to_tray": "Minimize to tray (not on window close)",
        "start_minimized_tray": "Start minimized to tray",
        "panic_hotkey": "Panic hotkey (Ctrl+Shift+Esc)",
        "panic_stealth": "Stealth panic (fake error)",
        "activity_sensitivity": "Activity sensitivity",
        "device_laptop": "Laptop",
        "device_desktop": "Desktop",
        "tray_show": "Show window",
        "tray_lock": "Lock vault",
        "tray_unlock": "Unlock",
        "tray_clear_clipboard": "Clear clipboard",
        "tray_panic": "Panic mode",
        "tray_tooltip_locked": "CryptoSafe — locked",
        "tray_tooltip_unlocked": "CryptoSafe — unlocked",
        "panic_activated": "Panic mode: vault locked.",
        "confirm_restore": "Restore vault from backup? Current database will be overwritten.",
        "confirm_destructive": "Confirm action",
        "profile_desc_standard": "Balanced (recommended).",
        "profile_desc_enhanced": "Shorter timeouts, lock on minimize.",
        "profile_desc_paranoid": "Maximum protection.",
        "device_profile_label": "Device type",
        "s6_export_title": "Export vault",
        "s6_import_title": "Import to vault",
        "s6_share_title": "Share entry",
        "s6_qr_title": "QR viewer",
        "s6_format": "Format",
        "s6_export_password": "Export password",
        "s6_public_key": "Recipient public key",
        "s6_public_key_ph": "Optional: recipient RSA key (from file or QR)",
        "s6_private_key": "Private key",
        "s6_private_key_ph": "Optional: your RSA private key when importing",
        "s6_encryption_settings": "Encryption settings",
        "s6_aes_bits": "AES bits",
        "s6_gzip": "GZIP compress",
        "s6_include_notes": "Include notes",
        "s6_entry_selection": "Entry selection",
        "s6_preview": "Preview",
        "s6_export_btn": "Export",
        "s6_import_btn": "Import",
        "s6_browse": "Browse…",
        "s6_file": "File",
        "s6_share_password": "Share password",
        "s6_conflict_mode": "Conflict mode",
        "s6_duplicate_policy": "Duplicates",
        "s6_preview_btn": "Preview",
        "s6_delivery": "Delivery method",
        "s6_permission": "Permission",
        "s6_expiration_days": "Expires (days)",
        "s6_generate_share": "Generate share package",
        "s6_payload": "Payload (JSON)",
        "s6_generate_qr": "Generate QR",
        "s6_scan_image": "Scan image",
        "s6_copy_payload": "Copy payload",
        "s6_export_failed": "Export failed: %s",
        "s6_import_failed": "Import failed: %s",
        "s6_share_failed": "Share failed: %s",
        "s6_export_done": "Export saved: %s",
        "s6_import_done": "Import: added %s, updated %s, skipped %s",
        "s6_share_done": "Share package created",
        "s6_invalid_pem": "Invalid RSA key. Leave the field empty or paste the full key from your exchange file.",
        "s6_select_entry_first": "Select an entry in the table first.",
        "s6_save_export": "Save export",
        "s6_select_import": "Select import file",
        "s6_fmt_encrypted_json": "Encrypted JSON",
        "s6_fmt_csv": "CSV (plain)",
        "s6_fmt_csv_enc": "CSV (encrypted JSON)",
        "s6_fmt_bw": "Bitwarden JSON",
        "s6_fmt_bw_enc": "Bitwarden (encrypted)",
        "s6_fmt_lp": "LastPass CSV",
        "s6_fmt_lp_enc": "LastPass (encrypted)",
        "s6_mode_merge": "Merge",
        "s6_mode_replace": "Replace",
        "s6_mode_dry": "Dry run",
        "s6_dup_skip": "Skip",
        "s6_dup_update": "Update",
        "s6_method_password": "File + password",
        "s6_method_pubkey": "RSA public key",
        "s6_method_link": "Link token",
        "s6_perm_readonly": "Read only",
        "s6_perm_edit": "Editable",
        "s6_qr_failed": "QR error: %s",
        "s6_preview_failed": "Preview: %s",
        "s6_col_entry": "Entry",
    },
}


SEARCH_FIELD_ALIASES = {
    "title": "title",
    "название": "title",
    "username": "username",
    "логин": "username",
    "login": "username",
    "url": "url",
    "notes": "notes",
    "заметки": "notes",
    "заметка": "notes",
}


def normalize_search_field(key: str):
    """Maps localized or English filter prefix to canonical field name."""
    return SEARCH_FIELD_ALIASES.get((key or "").strip().lower())


def t(key):
    """Looks up a localized string by key for the active language. / Возвращает локализованную строку по ключу для текущего языка."""
    lang = config.get(config.LANGUAGE, "ru")
    return STRINGS.get(lang, STRINGS["ru"]).get(key, key)
